export const TOKEN = 'YOUR_TOKEN_HERE';

export const cloudinaryInfo = {
  CLOUDINARY_NAME: '',
  CLOUDINARY_API_KEY: '',
  CLOUDINARY_API_SECRET: '',
  CLOUDINARY_IMAGE_UPLOAD_URL: '',
  CLOUDINARY_API_BASE_URL: '',
  CLOUDINARY_SECURE_DELIVERY_URL: '',
  CLOUDINARY_UPLOAD_PRESET: '',
};
